<a href="https://colab.research.google.com/github/Amaliaaap/Data-Mining/blob/main/PreProcessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Persiapan Data**

In [1]:
# Mengimport library yang digunakan (Pandas)
import pandas as pd

In [2]:
# membaca file CSV dan menyimpan datanya ke dalam sebuah DataFrame.
df = pd.read_csv('/content/drive/MyDrive/Data Mining/movie_sample_dataset.csv')
df.head()

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,200000000.0,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,44000000.0,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,usa,14000000.0,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,225000000.0,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000

**2. Memeriksa Data**

In [3]:
# Menampilkan baris pertama dari dataset
df.head(1)

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,100000000.0,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000

In [ ]:
# Memeriksa informasi umum tentang dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   color                 88 non-null     object
 1   director_name         88 non-null     object
 2   duration              99 non-null     int64
 3   gross                 91 non-null     float64
 4   genres                98 non-null     object
 5   movie_title           99 non-null     object
 6   title_year            99 non-null     int64
 7   language              99 non-null     object
 8   country               99 non-null     object
 9   budget                95 non-null     float64
 10  imdb_score            99 non-null     float64
 11  actors                99 non-null     object
 12  movie_facebook_likes  99 non-null     int64
dtypes: float64(3), int64(3), object(7)
memory usage: 10.2+ KB

In [ ]:
import numpy as np

# Memeriksa jumlah missing value di setiap kolom
print(df.isnull().sum())

color                   11
director_name           11
duration                 0
gross                    8
genres                   1
movie_title              0
title_year               0
language                 0
country                  0
budget                   4
imdb_score               0
actors                   0
movie_facebook_likes     0
dtype: int64

**3. Membersihkan Data**

In [ ]:
df.shape

(99, 13)

In [ ]:
df.loc[:, 'color'] = df['color'].str.strip().str.capitalize()
df.loc[:, 'country'] = df['country'].str.strip().str.upper()
df = df[(df['duration']>=0)&
              (df['gross']>=0)&
              (df['title_year']>=0)&
              (df['budget']>=0)&
              (df['imdb_score']>=0)&
              (df['movie_facebook_likes']>=0)]
df = df.replace('N/A', pd.NA)
df.dropna(inplace=True)
df

,color,director_name,duration,gross,genres,movie_title,title_year,language,country,budget,imdb_score,actors,movie_facebook_likes
0,Color,Martin Scorsese,240,116866727.0,Biography|Comedy|Crime|Drama,The Wolf of Wall Street,2013,English,USA,1.000000e+08,8.2,"Leonardo DiCaprio,Matthew McConaughey,Jon Favreau",138000
1,Color,Shane Black,195,408992272.0,Action|Adventure|Sci-Fi,Iron Man 3,2013,English,USA,2.000000e+08,7.2,"Robert Downey Jr.,Jon Favreau,Don Cheadle",95000
2,Color,Quentin Tarantino,187,54116191.0,Crime|Drama|Mystery|Thriller|Western,The Hateful Eight,2015,English,USA,4.400000e+07,7.9,"Craig Stark,Jennifer Jason Leigh,Zoë Bell",114000
3,Color,Kenneth Lonergan,186,46495.0,Drama,Margaret,2011,English,USA,1.400000e+07,6.5,"Matt Damon,Kieran Culkin,John Gallagher Jr.",0
4,Color,Peter Jackson,186,258355354.0,Adventure|Fantasy,The Hobbit: The Desolation of Smaug,2013,English,USA,2.250000e+08,7.9,"Aidan Turner,Adam Brown,James Nesbitt",83000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,Color,Steve McQueen,134,56667870.0,Biography|Drama|History,12 Years a Slave,2013,English,USA,2.000000e+07,8.1,"Quvenzhané Wallis,Scoot McNairy,Taran Killam",83000
95,Color,Richard J. Lewis,134,7501404.0,Comedy|Drama,Barney's Version,2010,English,CANADA,1.048570e+08,7.3,"Mark Addy,Atom Egoyan,Paul Gross",0
96,Color,Paul Greengrass,134,107100855.0,Biography|Drama|Thriller,Captain Phillips,2013,English,USA,5.500000e+07,7.9,"Tom Hanks,Chris Mulkey,Michael Chernus",65000
97,Color,David Ayer,134,85707116.0,Action|Drama|War,Fury,2014,English,USA,6.800000e+07,7.6,"Brad Pitt,Logan Lerman,Jim Parrack",82000
98,Color,Clint Eastwood,5,47034272.0,Biography|Drama|Music|Musical,Jersey Boys,2014,English,USA,4.000000e+07,6.9,"Johnny Cannizzaro,Steve Schirripa,Scott Vance",16000

In [ ]:
# Mengecek apakah masih ada Missing data
print(df.isnull().sum())

color                   0
director_name           0
duration                0
gross                   0
genres                  0
movie_title             0
title_year              0
language                0
country                 0
budget                  0
imdb_score              0
actors                  0
movie_facebook_likes    0
dtype: int64

4. Transformasi Data

In [ ]:
# Mengecek apa tipe data awal
df.dtypes

color                    object
director_name            object
duration                  int64
gross                   float64
genres                   object
movie_title              object
title_year                int64
language                 object
country                  object
budget                  float64
imdb_score              float64
actors                   object
movie_facebook_likes      int64
dtype: object

In [ ]:
# Mengubah tipe data
df['gross'] = df['gross'].astype('int')
df['budget'] = df['budget'].astype('int')
df.dtypes

color                    object
director_name            object
duration                  int64
gross                     int64
genres                   object
movie_title              object
title_year                int64
language                 object
country                  object
budget                    int64
imdb_score              float64
actors                   object
movie_facebook_likes      int64
dtype: object

In [10]:
df['genres'].str.split()
df['genres'].str.split(pat='|', expand = True)

            0          1         2         3        4
0   Biography     Comedy     Crime     Drama     None
1      Action  Adventure    Sci-Fi      None     None
2       Crime      Drama   Mystery  Thriller  Western
3       Drama       None      None      None     None
4   Adventure    Fantasy      None      None     None
..        ...        ...       ...       ...      ...
94  Biography      Drama   History      None     None
95     Comedy      Drama      None      None     None
96  Biography      Drama  Thriller      None     None
97     Action      Drama       War      None     None
98  Biography      Drama     Music   Musical     None

[99 rows x 5 columns]

In [11]:
df['actors'].str.split()
df['actors'].str.split(pat=',', expand = True)

                    0                     1                   2
0   Leonardo DiCaprio   Matthew McConaughey         Jon Favreau
1   Robert Downey Jr.           Jon Favreau         Don Cheadle
2         Craig Stark  Jennifer Jason Leigh            Zoë Bell
3          Matt Damon         Kieran Culkin  John Gallagher Jr.
4        Aidan Turner            Adam Brown       James Nesbitt
..                ...                   ...                 ...
94  Quvenzhané Wallis         Scoot McNairy        Taran Killam
95          Mark Addy           Atom Egoyan          Paul Gross
96          Tom Hanks          Chris Mulkey     Michael Chernus
97          Brad Pitt          Logan Lerman         Jim Parrack
98  Johnny Cannizzaro       Steve Schirripa         Scott Vance

[99 rows x 3 columns]

5. Penyimpanan Data

In [13]:
df.to_csv('movie_dataset_cleaned.csv', index=False)